apiVersion: v1
kind: Secret
metadata:
  name: app-secrets-dev
  namespace: merchant-payout-dev
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgresql:5432/payout_system"
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_DATASOURCE_PASSWORD: postgres
  JWT_SECRET: "dev-secret-key-12345"
  STRIPE_API_KEY_SG: "sk_test_dev_singapore"
  STRIPE_API_KEY_HK: "sk_test_dev_hongkong"
  STRIPE_API_KEY_MY: "sk_test_dev_malaysia"
  STRIPE_WEBHOOK_SECRET: "whsec_test_dev_webhook"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret-dev
  namespace: merchant-payout-dev
type: Opaque
stringData:
  password: postgres

