{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "merchant-payout-system.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "merchant-payout-system.labels" . | nindent 4 }}
{{- end }}

