demo.mode=true
spring.kafka.admin.auto-create=false

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

jwt.secret=${JWT_SECRET}
jwt.expiration=3600000

otp.expiration-minutes=5

# ===== Stripe Configuration =====
stripe.api-key-sg=${STRIPE_API_KEY_SG}
stripe.api-key-us=${STRIPE_API_KEY_US}
stripe.mock-base-url=${STRIPE_MOCK_BASE_URL}
stripe.mock-enabled=${STRIPE_MOCK_ENABLED}
stripe.skipSignatureCheck=${STRIPE_SKIP_SIGNATURE_CHECK}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET}

